FROM python:3.7.3-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint-prod.sh /tmp/entrypoint-prod.sh
RUN chmod +x /tmp/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/tmp/entrypoint-prod.sh"]